Repository BitcoinUnlimited/BitcoinUnlimited, pull requests merged in 2019-01, with the labels that each got.

#1534 rpc: Prevent `dumpwallet` from overwriting files
  qa/rpc-tests/wallet-dump.py
  src/wallet/rpcdump.cpp
Labels: ported

#1501 Enhancements to zerochecksum.py functional test
  qa/rpc-tests/test_framework/mininode.py
  qa/rpc-tests/zerochecksum.py
Labels: QA

#1524 Refactor tracking of thin type blocks in flight. (pre-req for compact blocks)
  qa/rpc-tests/thinblocks.py
  src/blockrelay/blockrelay_common.cpp
  src/blockrelay/blockrelay_common.h
  src/blockrelay/graphene.cpp
  src/blockrelay/graphene.h
  src/blockrelay/thinblock.cpp
  src/blockrelay/thinblock.h
  src/globals.cpp
  src/main.cpp
  src/net.cpp
  src/net.h
  src/net_processing.cpp
  src/parallel.cpp
  src/requestManager.cpp
  src/test/exploit_tests.cpp
  src/test/requestmanager_tests.cpp
Labels: P2P

#1525 Improve optimization
  src/blockrelay/graphene_set.cpp
  src/blockrelay/graphene_set.h
  src/test/graphene_tests.cpp
Labels: P2P

#1503 implement xversion changeable key
  contrib/devtools/xversionkeys.py
  qa/rpc-tests/test_framework/mininode.py
  qa/rpc-tests/test_framework/nodemessages.py
  qa/rpc-tests/xversion.py
  src/net.h
  src/net_processing.cpp
  src/protocol.cpp
  src/protocol.h
  src/xversionkeys.dat
Labels: P2P

#1434 Reduce scope of cs_main in ThreadCommitToMemPool()
  src/globals.cpp
  src/txadmission.cpp
  src/txmempool.cpp
Labels: Locking

#1449 Modify clang-format.py to make it work with python 3.x
  contrib/devtools/clang-format.py
Labels: Tools

#1450 Configure travis to use an Ubuntu 18.04 docker container
  .travis.yml
  contrib/devtools/clang-format.py
  qa/rpc-tests/mempool_persist.py
Labels: QA

#1520 net_processing: Remove gotWorkDone variable
  src/net_processing.cpp
Labels: Trivial

#1254 Disable a debug log category if prefixed with '-'
  qa/pull-tester/rpc-tests.py
  qa/rpc-tests/getlogcategories.py
  src/test/util_tests.cpp
  src/unlimited.cpp
  src/util.cpp
  src/util.h
Labels: enhancement

#1559 Improve travis caching
  .travis.yml
  .travis/after_failure.sh
  .travis/after_script.sh
  .travis/before_install.sh
  .travis/before_script.sh
  .travis/install.sh
  .travis/script.sh
Labels: QA, Tools

#1558 Update zmq to 4.3.1
  depends/packages/zeromq.mk
  doc/dependencies.md
Labels: DEPENDS

#1541 [UI] - Re-enable word wrap in peer details header
  src/qt/forms/debugwindow.ui
Labels: UI

#1532 Use canonical ordering in graphene
  qa/rpc-tests/ctor.py
  src/blockrelay/graphene.cpp
  src/net_processing.cpp
Labels: P2P

#1562 Move to cxx 14 and bump boost min ver to match
  .travis.yml
  configure.ac
Labels: REFACTOR

#1526 Simplify and update expedited code.
  src/expedited.cpp
  src/expedited.h
  src/validation/validation.cpp
Labels: P2P

#1540 [Windows Build Scripts] - Update cleanup script to remove previous build outputs
  build-aux/mingw/clean-bitcoin.bat
Labels: Tools

#1550 [Windows Build Scripts] - Update toolchain and dependencies versions.
  build-aux/mingw/SET_ENV_VARS.bat
  build-aux/mingw/clean-bitcoin.sh
  build-aux/mingw/config-mingw.bat
  build-aux/mingw/install-deps.sh
  build-aux/mingw/install-toolchain.sh
  build-aux/mingw/make-bitcoin.sh
  build-aux/mingw/rebuild-bitcoin.bat
  depends/patches/libpng/mingw-line-ending-fix.patch
  depends/patches/qt/fix_qt571_win32_qmake.patch
Labels: Tools

#1564 reduce number of nodes (resource usage) in getlogcategories.py
  qa/rpc-tests/getlogcategories.py
Labels: QA

#1560 Create error(ctgr, ...) that allows us to specify a logging category
  src/blockrelay/graphene.cpp
  src/httpserver.cpp
  src/qt/bitcoin.cpp
  src/respend/respenddetector.cpp
  src/test/test_bitcoin.cpp
  src/unlimited.cpp
  src/util.h
  src/validation/validation.cpp
Labels: LOG, enhancement

#1574 Propaedeutic changes needed to move the gitian build to Ubuntu 18.04
  configure.ac
  contrib/devtools/symbol-check.py
  src/Makefile.am
  src/compat/glibc_compat.cpp
  src/init.cpp
Labels: QA, Tools, ported

#1570 Add missing lock in FindNextBlocksToDownload()
  src/net_processing.cpp
  src/requestManager.cpp
  src/rpc/blockchain.cpp
Labels: Locking, P2P

#1573 Fix several potential issues found by sanitizers
  src/utiltime.cpp
Labels: ported

#1577 Use UniValue.pushKV rather than push_back(Pair())
  src/bitcoin-miner.cpp
  src/rest.cpp
  src/rpc/blockchain.cpp
  src/rpc/mining.cpp
  src/rpc/misc.cpp
  src/rpc/net.cpp
  src/rpc/protocol.cpp
  src/rpc/rawtransaction.cpp
  src/stat.h
  src/tweak.cpp
  src/univalue/gen/gen.cpp
  src/univalue/include/univalue.h
  src/univalue/lib/univalue.cpp
  src/univalue/lib/univalue_read.cpp
  src/univalue/lib/univalue_write.cpp
  src/univalue/test/object.cpp
  src/univalue/test/unitester.cpp
  src/unlimited.cpp
  src/wallet/rpcwallet.cpp
Labels: ported, subtree

#1566 Cleanup FinalizeNode()
  src/main.cpp
  src/nodestate.cpp
  src/nodestate.h
  src/requestManager.cpp
  src/requestManager.h
  src/validation/validation.cpp
Labels: P2P
