Repository BitcoinUnlimited/BitcoinUnlimited, pull requests merged in 2019-04, with the labels that each got.

#1629 [util] Add method http_get
  src/.formatted-files
  src/Makefile.am
  src/Makefile.test.include
  src/test/utilhttp_tests.cpp
  src/utilhttp.cpp
  src/utilhttp.h
Labels: RPC

#1636 add rpm build instructions
  doc/build-unix-rpm.md
Labels: DOC

#1649 Improve reliablility of p2p-acceptblock.py
  qa/rpc-tests/p2p-acceptblock.py
Labels: QA

#1650 Improve reliablility of sendheaders.py
  qa/rpc-tests/sendheaders.py
Labels: QA

#1644 Activate November 15th 2018 upgrade by height
  qa/pull-tester/rpc-tests.py
  qa/rpc-tests/compactblocks_2.py
  qa/rpc-tests/ctor.py
  qa/rpc-tests/mining_ctor.py
  qa/rpc-tests/validateblocktemplate.py
  src/chain.cpp
  src/chain.h
  src/chainparams.cpp
  src/consensus/params.h
  src/globals.cpp
  src/init.cpp
  src/miner.cpp
  src/protocol.h
  src/txadmission.cpp
  src/unlimited.cpp
  src/validation/forks.cpp
  src/validation/forks.h
  src/validation/validation.cpp
Labels: consensus

#1603 Allow Graphene to use variant of CFastFilter
  qa/pull-tester/rpc-tests.py
  qa/rpc-tests/graphene_optimized.py
  src/blockrelay/graphene.cpp
  src/blockrelay/graphene.h
  src/blockrelay/graphene_set.cpp
  src/blockrelay/graphene_set.h
  src/fastfilter.h
  src/globals.cpp
  src/net_processing.cpp
  src/test/fastfilter_tests.cpp
  src/test/graphene_tests.cpp
  src/xversionkeys.dat
Labels: P2P

#1648 Add SCRIPT_ALLOW_SEGWIT_RECOVERY
  qa/pull-tester/rpc-tests.py
  qa/rpc-tests/segwit-recovery-activation.py
  src/script/interpreter.cpp
  src/script/script.cpp
  src/script/script.h
  src/script/sigcache.cpp
  src/test/data/script_tests.json
  src/test/script_tests.cpp
  src/test/scriptflags.cpp
  src/test/sigcache_tests.cpp
  src/txadmission.cpp
  src/validation/validation.cpp
Labels: consensus

#1611 Refactor Xthin data out of CNode
  src/blockrelay/blockrelay_common.cpp
  src/blockrelay/blockrelay_common.h
  src/blockrelay/compactblock.cpp
  src/blockrelay/graphene.cpp
  src/blockrelay/thinblock.cpp
  src/blockrelay/thinblock.h
  src/net.cpp
  src/net.h
  src/net_processing.cpp
  src/primitives/block.h
  src/test/exploit_tests.cpp
  src/test/thinblock_data_tests.cpp
  src/unlimited.cpp
Labels: P2P, REFACTOR

#1633 Basic integration with the electrum server electrs
  Makefile.am
  contrib/electrs/build_electrs.py
  contrib/gitian-descriptors/gitian-linux.yml
  qa/pull-tester/rpc-tests.py
  qa/rpc-tests/electrum_basics.py
  qa/rpc-tests/getlogcategories.py
  src/.formatted-files
  src/Makefile.am
  src/allowed_args.cpp
  src/electrum/electrs.cpp
  src/electrum/electrs.h
  src/electrum/electrumserver.cpp
  src/electrum/electrumserver.h
  src/init.cpp
  src/rpc/electrum.cpp
  src/rpc/register.h
  src/util.h
Labels: Tools, wallet

#1623 [Builds on 1611] Refactor compact blocks out of CNode
  src/blockrelay/blockrelay_common.cpp
  src/blockrelay/blockrelay_common.h
  src/blockrelay/compactblock.cpp
  src/blockrelay/compactblock.h
  src/blockrelay/thinblock.cpp
  src/blockrelay/thinblock.h
  src/net.cpp
  src/net.h
  src/parallel.cpp
  src/primitives/block.h
  src/test/exploit_tests.cpp
  src/test/thinblock_data_tests.cpp
  src/unlimited.cpp
Labels: REFACTOR
