Repository BitcoinUnlimited/BitcoinUnlimited, pull requests merged in 2019-02, with the labels that each got.

#1543 Implement Compact Blocks BIP152
  qa/pull-tester/rpc-tests.py
  qa/rpc-tests/compactblocks_1.py
  qa/rpc-tests/compactblocks_2.py
  qa/rpc-tests/getlogcategories.py
  qa/rpc-tests/sendheaders.py
  qa/rpc-tests/test_framework/mininode.py
  qa/rpc-tests/test_framework/nodemessages.py
  qa/rpc-tests/test_framework/siphash.py
  src/Makefile.am
  src/Makefile.test.include
  src/allowed_args.cpp
  src/blockrelay/blockrelay_common.cpp
  src/blockrelay/blockrelay_common.h
  src/blockrelay/compactblock.cpp
  src/blockrelay/compactblock.h
  src/blockrelay/graphene.cpp
  src/blockrelay/graphene.h
  src/blockrelay/thinblock.cpp
  src/blockrelay/thinblock.h
  src/globals.cpp
  src/init.cpp
  src/main.cpp
  src/main.h
  src/net.cpp
  src/net.h
  src/net_processing.cpp
  src/parallel.cpp
  src/protocol.cpp
  src/protocol.h
  src/qt/clientmodel.cpp
  src/qt/clientmodel.h
  src/qt/forms/debugwindow.ui
  src/qt/rpcconsole.cpp
  src/qt/rpcconsole.h
  src/requestManager.cpp
  src/requestManager.h
  src/rpc/net.cpp
  src/test/compactblocks_tests.cpp
  src/test/exploit_tests.cpp
  src/test/hash_tests.cpp
  src/test/requestmanager_tests.cpp
  src/uint256.h
  src/unlimited.cpp
  src/unlimited.h
  src/util.h
  src/version.h
  src/xversionkeys.dat
Labels: P2P

#1594 Build gitian using Ubuntu 18.04 based docker containers
  configure.ac
  contrib/gitian-descriptors/gitian-arm.yml
  contrib/gitian-descriptors/gitian-linux.yml
  contrib/gitian-descriptors/gitian-osx.yml
  contrib/gitian-descriptors/gitian-win-signer.yml
  contrib/gitian-descriptors/gitian-win.yml
  depends/packages/bdb.mk
  depends/packages/boost.mk
  depends/packages/protobuf.mk
  depends/packages/qt.mk
  doc/gitian-building-bu.md
  src/compat/glibc_compat.cpp
Labels: QA

#1572 Update helper text for outscript= to reflect actual usage
  src/bitcoin-tx.cpp
Labels: DOC

#1557 Udpate qt depends
  build-aux/m4/bitcoin_qt.m4
  contrib/gitian-descriptors/gitian-linux.yml
  contrib/gitian-descriptors/gitian-osx.yml
  contrib/gitian-descriptors/gitian-win.yml
  depends/packages/freetype.mk
  depends/packages/libICE.mk
  depends/packages/libSM.mk
  depends/packages/packages.mk
  depends/packages/qt.mk
  depends/packages/xextproto.mk
  depends/patches/qt/fix-cocoahelpers-macos.patch
  depends/patches/qt/fix-xcb-include-order.patch
  depends/patches/qt/fix_configure_mac.patch
  depends/patches/qt/fix_no_printer.patch
  depends/patches/qt/fix_rcc_determinism.patch
  depends/patches/qt/mac-qmake.conf
  depends/patches/qt/mingw-uuidof.patch
  depends/patches/qt/pidlist_absolute.patch
  depends/patches/qt/qfixed-coretext.patch
  depends/patches/qt/xkb-default.patch
  depends/patches/qt46/stlfix.patch
  doc/dependencies.md
  src/Makefile.am
  src/Makefile.qt.include
  src/qt/test/test_main.cpp
Labels: DEPENDS

#1597 Reset default -g -O2 flags when enable debug
  configure.ac
Labels: ported

#1565 [DOC] update dependency chart to reflect changes made in #1562
  doc/dependencies.md
Labels: DOC

#1588 Cleanup XVal
  src/blockrelay/compactblock.cpp
  src/blockrelay/graphene.cpp
  src/blockrelay/thinblock.cpp
  src/blockrelay/thinblock.h
  src/globals.cpp
  src/net.h
  src/parallel.cpp
  src/primitives/block.h
  src/unlimited.cpp
  src/validation/validation.cpp
Labels: consensus, validation
