Repository BitcoinUnlimited/BitcoinUnlimited, pull requests merged in 2019-03, with the labels that each got.

#1581 Documentation - Clean up the documentation
  CONTRIBUTING.md
  INSTALL
  INSTALL.md
  README.md
  contrib/debian/copyright
  doc/README.md
  doc/README_windows.txt
  doc/REST-interface.md
  doc/bip135-genvbvoting-condensed-requirements.md
  doc/bip135-genvbvoting.md
  doc/bu-parallel-validation.md
  doc/bu-xpedited-forwarding.md
  doc/bu-xthin-protocol.md
  doc/bu-xthin.md
  doc/bug-triage.md
  doc/build-macos.md
  doc/build-openbsd.md
  doc/build-unix.md
  doc/build-windows-mingw.md
  doc/build-windows.md
  doc/dependencies.md
  doc/developer-notes.md
  doc/dnsseed-policy.md
  doc/fuzzing.md
  doc/gitian-building.md
  doc/init.md
  doc/miner.md
  doc/multiwallet-qt.md
  doc/quick-install.md
  doc/reduce-traffic.md
  doc/shared-libraries.md
  doc/tor.md
  doc/unit-tests.md
  doc/xversionmessage.md
Labels: DOC

#1575 add a few batch rpc calls
  qa/pull-tester/rpc-tests.py
  qa/rpc-tests/getrawtransaction.py
  qa/rpc-tests/merkle_blocks.py
  src/primitives/transaction.cpp
  src/primitives/transaction.h
  src/rpc/rawtransaction.cpp
Labels: RPC

#1609 Port core PR #10775: nCheckDepth chain height fix
  src/validation/verifydb.cpp
Labels: ported

#1610 Prepare for May 15th 2019 protocol upgrade
  src/.formatted-files
  src/Makefile.am
  src/main.cpp
  src/rpc/rawtransaction.cpp
  src/test/txvalidationcache_tests.cpp
  src/test/uahf_test.cpp
  src/txadmission.cpp
  src/uahf_fork.cpp
  src/uahf_fork.h
  src/unlimited.h
  src/validation/forks.cpp
  src/validation/forks.h
  src/validation/validation.cpp
  src/wallet/wallet.cpp
Labels: consensus

#1551 Use SipHash for cheap hashes in Graphene
  src/blockrelay/graphene.cpp
  src/blockrelay/graphene.h
  src/blockrelay/graphene_set.cpp
  src/blockrelay/graphene_set.h
  src/net.h
  src/net_processing.cpp
  src/test/graphene_tests.cpp
  src/test/test_bitcoin_fuzzy.cpp
Labels: P2P

#1582 Seed IBLT hash functions
  src/blockrelay/graphene.cpp
  src/blockrelay/graphene.h
  src/blockrelay/graphene_set.cpp
  src/blockrelay/graphene_set.h
  src/iblt.cpp
  src/iblt.h
  src/net.h
  src/net_processing.cpp
  src/test/graphene_tests.cpp
  src/test/iblt_tests.cpp
Labels: P2P

#1601 Fix typos in net_processing and requestManager comments
  doc/graphene-specification-v1.mediawiki
  doc/media/graphene-messaging.png
  src/net_processing.cpp
  src/requestManager.cpp
  src/version.h
Labels: Trivial

#1606 [rpc] Add initialblockdownload to getblockchaininfo
  qa/rpc-tests/blockchain.py
  src/rpc/blockchain.cpp
Labels: RPC

#1612 [rpc] Allow fetching tx directly from specified block in getrawtransaction
  qa/rpc-tests/rawtransactions.py
  src/main.cpp
  src/main.h
  src/rpc/rawtransaction.cpp
  src/rpc/server.cpp
Labels: RPC

#1402 DRY refactor in rpc/blockchain.cpp
  src/rpc/blockchain.cpp
  src/versionbits.h
Labels: REFACTOR

#1627 [qa] Support setup_clean_chain, extra_args and num_nodes
  qa/rpc-tests/bip135basic.py
  qa/rpc-tests/maxblocksinflight.py
  qa/rpc-tests/maxuploadtarget.py
  qa/rpc-tests/mining_ctor.py
  qa/rpc-tests/test_framework/test_framework.py
Labels: QA

#1630 Boost 1.66
  .travis.yml
  .travis/script_a.sh
  .travis/script_b.sh
  build-aux/m4/ax_boost_system.m4
  depends/packages/boost.mk
  src/test/test_bitcoin.cpp
Labels: DEPENDS

#1634 [doc] Remove outdated Gitian build guide
  contrib/gitian-descriptors/README.md
Labels: DOC

#1631 Schnorr2
  qa/rpc-tests/checkdatasig_activation.py
  qa/rpc-tests/test_framework/cashlib/cashlib.py
  src/Makefile.test.include
  src/script/interpreter.cpp
  src/script/interpreter.h
  src/script/script_error.h
  src/script/sigcache.cpp
  src/script/sigcache.h
  src/secp256k1/src/modules/recovery/main_impl.h
  src/secp256k1/src/modules/recovery/tests_impl.h
  src/secp256k1/src/secp256k1.c
  src/test/data/script_tests.json
  src/test/data/txcreatesign.hex
  src/test/key_tests.cpp
  src/test/lcg.h
  src/test/lcg_tests.cpp
  src/test/schnorr_tests.cpp
  src/test/script_tests.cpp
  src/test/scriptflags.cpp
  src/test/sigcache_tests.cpp
  test/util/data/txcreatesignv1.json
  test/util/data/txcreatesignv2.hex
Labels: consensus
